package com.changenode;

import javax.swing.*;
import java.awt.*;

public class BaseForm {
    public JTextArea textArea;
    public JToolBar toolBar;
    public JLabel statusLabel;
    public JPanel panel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new BorderLayout(0, 0));
        toolBar = new JToolBar();
        panel.add(toolBar, BorderLayout.NORTH);
        textArea = new JTextArea();
        textArea.setLineWrap(true);
        panel.add(textArea, BorderLayout.CENTER);
        statusLabel = new JLabel();
        statusLabel.setText("Status");
        panel.add(statusLabel, BorderLayout.SOUTH);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
